substitutions:
    _APP_HOSTING_REGION: 'us-central1'
    _APP_HOSTING_BACKEND: 'fb-app-hosting-backend'
    _PUBLIC_FUNCTIONS: 'fbFunction1' # Space-separated list of function names

steps:
    # Git LFS Pull
    - name: 'alpine/git'
      secretEnv: ['GITHUB_TOKEN']
      entrypoint: 'sh'
      args:
          - '-c'
          - |
              git config --global credential.helper "" && \
              git config --global url."https://x-access-token:$$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/" && \
              apk add git-lfs && \
              git lfs install && \
              git lfs pull
      id: 'git-lfs-pull'

    - name: 'node:22'
      entrypoint: 'npx'
      args: ['-y', 'pnpm', 'install', '--frozen-lockfile']
      id: 'install-deps'

    # Lint
    - name: 'node:22'
      entrypoint: 'npx'
      args: ['-y', 'pnpm', 'run', 'lint']
      id: 'lint'
      waitFor: ['install-deps']

    # Test
    - name: 'node:22'
      entrypoint: 'npx'
      args: ['-y', 'pnpm', 'run', 'test']
      id: 'test'
      waitFor: ['install-deps']

    # Build
    - name: 'node:22'
      entrypoint: 'npx'
      args: ['-y', 'pnpm', 'run', 'build']
      id: 'build'
      waitFor: ['install-deps', 'git-lfs-pull']

    # Deploy
    - name: 'node:22'
      entrypoint: 'npx'
      args:
          [
              '-y',
              'pnpm',
              '--filter',
              'scripts',
              'prepare-apps-for-deploy',
              '--app',
              'fb-app-hosting',
              '--packages',
              '@packages/ui',
          ]
      id: 'prepare-app-hosting'
      waitFor: ['build', 'test', 'lint']

    - name: 'node:22'
      entrypoint: 'npx'
      args:
          [
              '-y',
              'pnpm',
              '--filter',
              'scripts',
              'prepare-apps-for-deploy',
              '--app',
              'fb-functions',
              '--packages',
              '@packages/ui',
          ]
      id: 'prepare-functions'
      waitFor: ['build', 'test', 'lint']

    - name: 'node:22'
      entrypoint: 'npx'
      args:
          [
              '-y',
              'firebase-tools',
              'deploy',
              '--only',
              'hosting,apphosting,functions',
              '--project',
              '$PROJECT_ID',
              '--message',
              'Cloud Build $BUILD_ID',
              '--force',
          ]
      id: 'deploy'
      waitFor: ['prepare-app-hosting', 'prepare-functions']

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              if [ -n "${_PUBLIC_FUNCTIONS}" ]; then
                for func in ${_PUBLIC_FUNCTIONS}; do
                  echo "Setting public access for function: $func"
                  gcloud functions add-invoker-policy-binding $func \
                    --region=${_APP_HOSTING_REGION} \
                    --member=allUsers \
                    --project=$PROJECT_ID
                done
              else
                echo "No public functions specified."
              fi
      id: 'set-public-access'
      waitFor: ['deploy']

    - name: 'node:22'
      entrypoint: 'npx'
      args:
          [
              '-y',
              'pnpm',
              '--filter',
              'scripts',
              'verify-app-hosting-rollout',
              '--project',
              '$PROJECT_ID',
              '--location',
              '${_APP_HOSTING_REGION}',
              '--backend',
              '${_APP_HOSTING_BACKEND}',
          ]
      id: 'verify-rollout'
      waitFor: ['deploy']

options:
    logging: CLOUD_LOGGING_ONLY

availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest
          env: 'GITHUB_TOKEN'
