substitutions:
    _APP_HOSTING_REGION: 'us-central1'
    _APP_HOSTING_BACKEND: 'fb-app-hosting-backend'
    _PUBLIC_FUNCTIONS: 'fbFunction1' # Space-separated list of function names
    _AR_REPO_LOCATION: 'us-central1'
    _AR_REPO_NAME: 'app-hosting-repo'

steps:
    # Git LFS Pull
    - name: 'alpine/git'
      secretEnv: ['GITHUB_TOKEN']
      entrypoint: 'sh'
      args:
          - '-c'
          - |
              git config --global credential.helper "" && \
              git config --global url."https://x-access-token:$$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/" && \
              apk add git-lfs && \
              git lfs install && \
              git lfs pull
      id: 'git-lfs-pull'

    - name: 'node:22'
      entrypoint: 'npx'
      args: ['-y', 'pnpm', 'install', '--frozen-lockfile']
      id: 'install-deps'

    # Lint
    - name: 'node:22'
      entrypoint: 'npx'
      args: ['-y', 'pnpm', 'run', 'lint']
      id: 'lint'
      waitFor: ['install-deps']

    # Test
    - name: 'node:22'
      entrypoint: 'npx'
      args: ['-y', 'pnpm', 'run', 'test']
      id: 'test'
      waitFor: ['install-deps']

    # Build
    - name: 'node:22'
      entrypoint: 'npx'
      args: ['-y', 'pnpm', 'run', 'build']
      id: 'build'
      waitFor: ['install-deps', 'git-lfs-pull']

    # Deploy Functions & Hosting (Firebase)
    - name: 'node:22'
      entrypoint: 'npx'
      args:
          [
              '-y',
              'pnpm',
              '--filter',
              'scripts',
              'prepare-apps-for-deploy',
              '--app',
              'fb-functions',
              '--packages',
              '@packages/ui',
          ]
      id: 'prepare-functions'
      waitFor: ['build', 'test', 'lint']

    - name: 'node:22'
      entrypoint: 'npx'
      args:
          [
              '-y',
              'firebase-tools',
              'deploy',
              '--only',
              'hosting,functions',
              '--project',
              '$PROJECT_ID',
              '--message',
              'Cloud Build $BUILD_ID',
              '--force',
          ]
      id: 'deploy-firebase'
      waitFor: ['prepare-functions']

    # Deploy App Hosting (Cloud Run)
    - name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              docker build -t ${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/fb-app-hosting:$COMMIT_SHA -f apps/fb-app-hosting/Dockerfile apps/fb-app-hosting
      id: 'build-container'
      waitFor: ['build', 'test', 'lint']

    - name: 'gcr.io/cloud-builders/docker'
      args:
          [
              'push',
              '${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/fb-app-hosting:$COMMIT_SHA',
          ]
      id: 'push-container'
      waitFor: ['build-container']

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args:
          [
              'run',
              'deploy',
              '${_APP_HOSTING_BACKEND}',
              '--image',
              '${_AR_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/fb-app-hosting:$COMMIT_SHA',
              '--region',
              '${_APP_HOSTING_REGION}',
              '--project',
              '$PROJECT_ID',
          ]
      id: 'deploy-cloud-run'
      waitFor: ['push-container']

options:
    logging: CLOUD_LOGGING_ONLY

availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest
          env: 'GITHUB_TOKEN'
